// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimpleNotes.Infrastructure.DbContexts;
using SimpleNotes.Infrastructure.Enums;

#nullable disable

namespace SimpleNotes.Infrastructure.Migrations
{
    [DbContext(typeof(NotesDbContext))]
    [Migration("20240508150156_AddLabel")]
    partial class AddLabel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "node_type", new[] { "folder", "note" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "ltree");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SimpleNotes.Infrastructure.Entities.Label", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.ToTable("Labels", t =>
                        {
                            t.HasCheckConstraint("CK_Notes_ColorRegEx", "Color ~* '^#[a-f0-9]{6}$");
                        });
                });

            modelBuilder.Entity("SimpleNotes.Infrastructure.Entities.TreeNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("ltree");

                    b.Property<NodeType>("Type")
                        .HasColumnType("node_type");

                    b.HasKey("Id");

                    b.HasIndex("Path");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Path"), "GIST");

                    b.ToTable("TreeNodes");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SimpleNotes.Infrastructure.Entities.TreeNodeLabel", b =>
                {
                    b.Property<Guid>("LabelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TreeNodeId")
                        .HasColumnType("uuid");

                    b.HasKey("LabelId", "TreeNodeId");

                    b.HasIndex("TreeNodeId");

                    b.ToTable("TreeNodeLabels");
                });

            modelBuilder.Entity("SimpleNotes.Infrastructure.Entities.Note", b =>
                {
                    b.HasBaseType("SimpleNotes.Infrastructure.Entities.TreeNode");

                    b.Property<string>("Text")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("SimpleNotes.Infrastructure.Entities.TreeNodeLabel", b =>
                {
                    b.HasOne("SimpleNotes.Infrastructure.Entities.Label", "Label")
                        .WithMany("TreeNodeLabels")
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleNotes.Infrastructure.Entities.TreeNode", "TreeNode")
                        .WithMany("TreeNodeLabels")
                        .HasForeignKey("TreeNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Label");

                    b.Navigation("TreeNode");
                });

            modelBuilder.Entity("SimpleNotes.Infrastructure.Entities.Note", b =>
                {
                    b.HasOne("SimpleNotes.Infrastructure.Entities.TreeNode", null)
                        .WithOne()
                        .HasForeignKey("SimpleNotes.Infrastructure.Entities.Note", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SimpleNotes.Infrastructure.Entities.Label", b =>
                {
                    b.Navigation("TreeNodeLabels");
                });

            modelBuilder.Entity("SimpleNotes.Infrastructure.Entities.TreeNode", b =>
                {
                    b.Navigation("TreeNodeLabels");
                });
#pragma warning restore 612, 618
        }
    }
}
